# This is a basic workflow to help you get started with Actions

name: debug workflow
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev_actions ]
  pull_request:
    branches: [ dev_actions ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}

  test_job_env:
    name: test by @${{ github.actor }}
    steps:
      - name: git respo
        id: git_resp
        run: |
          echo ${{ github.repository }}

#  env_test:
##    strategy:
##      matrix:
##        python-versions:
##          - 3.7
##          - 3.10.9
##        os:
##          - ubuntu-18.04
##          - macos-latest
##    runs-on: ${{ matrix.os }}
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        python-versions: [ 3.10.9 ]
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-versions }}
#
#      - name: list files
#        run: ls -l .
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install poetry
